name: 🐞 Bug Report
description: File a bug report
labels: ['🐞 Bug']
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to file a bug report! Please fill out this form as completely as possible.
  - type: dropdown
    id: os
    attributes:
      label: What operating system are you using?
      options:
        - Mac
        - Windows
        - Linux
        - Other
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior, please provide a clear code snippets that always reproduces the issue or a GitHub repository. Screenshots can be provided in the issue body below.
    validations:
      required: true
  - type: markdown
    attributes:
      value: Thanks in advance!
