name: CI

on:
  pull_request:
    branches: ['*']

jobs:
  lint-pr-title:
    runs-on: ubuntu-latest
    name: Validate PR Title
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  lint:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'

      - uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          run_install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - run: pnpm lint

  prettier:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'

      - uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          run_install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - run: pnpm format:check
